[versions]
accompanist = "0.23.1"

[libraries]
pager = { module = "com.google.accompanist:accompanist-pager", version.ref ="accompanist" }
pagerIndicator = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
insets = { module = "com.google.accompanist:accompanist-insets", version.ref ="accompanist" }
systemUiController = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
swipeRefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
navAnimation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
navMaterial = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }