[versions]
lifecycle = "2.5.0-alpha03"
work = "2.7.1"

[libraries]
agp = "com.android.tools.build:gradle:7.1.2"
core = "androidx.core:core-ktx:1.8.0-alpha05"
appCompat = "androidx.appcompat:appcompat:1.6.0-alpha01"
browser = "androidx.browser:browser:1.4.0"
webkit = "androidx.webkit:webkit:1.4.0"
sqlite = "androidx.sqlite:sqlite-ktx:2.3.0-alpha01"
dataStore = "androidx.datastore:datastore-preferences:1.0.0"
emoji = "androidx.emoji2:emoji2-views:1.1.0"

compose-activity = "androidx.activity:activity-compose:1.5.0-alpha03"
compose-navigation = "androidx.navigation:navigation-compose:2.5.0-alpha03"
compose-gradle = "org.jetbrains.compose:compose-gradle-plugin:1.1.0"

lifecycle-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref ="lifecycle" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref ="lifecycle" }

work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "work"}
