[versions]
lifecycle = "2.9.4"
work = "2.11.1"
[libraries]
core = "androidx.core:core-ktx:1.17.0"
media = "androidx.media:media:1.7.1"
appCompat = "androidx.appcompat:appcompat:1.7.1"
browser = "androidx.browser:browser:1.9.0"
activity = "androidx.activity:activity-ktx:1.12.4"
webkit = "androidx.webkit:webkit:1.15.0"
dataStore = "androidx.datastore:datastore-preferences:1.2.0"
emoji = "androidx.emoji2:emoji2-views:1.6.0"
biometric = "androidx.biometric:biometric-ktx:1.2.0-alpha05"
security-crypto = "androidx.security:security-crypto:1.1.0"
documentfile = "androidx.documentfile:documentfile:1.1.0"
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodelktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }

