[versions]
lifecycle = "2.6.0-alpha01"
work = "2.8.0-alpha02"

[libraries]
core = "androidx.core:core-ktx:1.9.0-alpha05"
media = "androidx.media:media:1.6.0"
appCompat = "androidx.appcompat:appcompat:1.6.0-alpha05"
browser = "androidx.browser:browser:1.4.0"
webkit = "androidx.webkit:webkit:1.5.0-beta01"
dataStore = "androidx.datastore:datastore-preferences:1.0.0"
dataStoreCore = "androidx.datastore:datastore-preferences-core:1.0.0"
emoji = "androidx.emoji2:emoji2-views:1.2.0-beta01"
biometric = "androidx.biometric:biometric-ktx:1.2.0-alpha04"

compose-navigation = "androidx.navigation:navigation-compose:2.5.3"
compose-gradle = "org.jetbrains.compose:compose-gradle-plugin:1.1.0"

lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodelktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }

work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }

